### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by s0undt3ch** [noirello/bonsai#14]
Sorry to create an issue just to ask this bit, has development stopped?

**Comment by noirello** [comment]
This project started as a hobby project during my university years, and not long after I'd made my first release it was used in one of the courses where I helped around, which gave me a boost and a lot of feedbacks.

But now the course is no longer running, my university studies are finished and I'm working in a different area of IT these days which causes that I've less time for the project unfortunately.

So the development has definitely slowed down and I can't make any promises, but I'm not ready to let go this project, not yet anyway. :)

**Comment by s0undt3ch** [comment]
Awesome! The reason I found the project was that I needed an asyncio LDAP library, but I needed to know if the investment of switching the LDAP client library would pay off or if development was just stopped.

Thanks!

**Comment by noirello** [comment]
With your permission, I'd like to close this ticket. Finding a _Dead Project?_ issue on the top of the issue site doesn't do any good to the project's PR. ;)

**Comment by s0undt3ch** [comment]
Closed! :smile:
