### ISSUE TITLE
FutureWarning: Possible nested set for re on python 3.7

### ISSUE THREAD

**Issue by garyvdm** [noirello/bonsai#22]
When using bonsai with python 3.7 I get this warning:

    .../lib/python3.7/site-packages/bonsai/ldapurl.py:44: FutureWarning: Possible nested set at position 52

**Comment by noirello** [comment]
Thanks, it will be fixed in the next release (already fixed on the [refactor ](https://github.com/noirello/bonsai/tree/refactor) branch).

**Comment by noirello** [comment]
v1.0.0 is out, the issues is fixed.
