### ISSUE TITLE
Question: Connection Pooling

### ISSUE THREAD

**Issue by schlitzered** [noirello/bonsai#23]
is there a connection pool in place, or do i have to build my own connection pool on top of this library?

**Comment by noirello** [comment]
No, there isn't, sorry. You have to build your own.
But a contribution about this would be much appreciated. :)

**Comment by schlitzered** [comment]
i take a look.

i guess the easiest thing would be to implement the connection pool directly in LDAPClient.

i think of adding a new parameter to __init__ that will be called pool_size.

i will then add a acquire and release function, that can be used to get & return LDAPConnection objects. 

i would also implement __enter__ and __exit__ functions, so LDAPClient can be used as a context manager.

what do you think?

**Comment by noirello** [comment]
I know, quite some time has passed, but I've added some connection pool classes that are currently on the [feature/pool](https://github.com/noirello/bonsai/tree/feature/pool) branch.
I'm planning to include these modifications in the next release (that'll happen in a few days with some luck). 
If you have any thoughts about it, please share them.

**Comment by noirello** [comment]
Basic pool functionality is available now in 1.1.0.
