### ISSUE TITLE
True async?

### ISSUE THREAD

**Issue by rmk135** [noirello/bonsai#24]
Hi there,

Quick question, when I do async connect is it thread-pooled or is it going truly async?

```python
async with client.connect(is_async=True) as conn:
        res = await conn.search("ou=nerdherd,dc=bonsai,dc=test", 2)
        print(res)
        who = await conn.whoami()
        print(who)
```

Thanks,
Roman

**Comment by noirello** [comment]
Hi, the short answer is that it's truly async. The underlying C lib (openldap/winldap) uses a poll mechanism on the file descriptor. As far as I know, no threads are involved.

The longer answer that every connection build-up is spawning a thread for different reasons in the module on different platforms. On Linux the OpenLDAP initialisation includes file reads for configuration which is done in a separate thread not in the main thread of Python's interpreter. On Windows besides the initialisation, the possible TLS build-up and binding to an LDAP server are all done in this separate thread.

**Comment by rmk135** [comment]
Ok, I see! Thanks for detailed answer and such a great library!

PS: huge respect that it’s done as extension type! :)
