### ISSUE TITLE
bonsai.errors.LDAPError: Operations error

### ISSUE THREAD

**Issue by reach4bawer** [noirello/bonsai#34]
Hi, I am running into the following error with the code. 

I am working with a virtual active directory connection,(Ldap3 over SSL)

Code: 
```
compiled_search_filter = '(&(objectCategory=person)(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=ADgroup,OU=test,OU=sys,DC=a,DC=b,DC=com))'
async with client.connect(is_async=True) as conn:
        res = []
        result = await conn.paged_search(base="", scope=2, filter_exp=compiled_search_filter,
                                         attrlist=['employeeID', 'sAMAccountName','objectClass','DistinguishedName'],
                                         timeout=10,attrsonly=True,page_size=1000)
        async for r in result:
            res.append(r)
```

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-9347d89bb5c8>", line 1, in <module>
>     runfile('/Users/bawer/Documents/Automation Projects/Test/Bonsai_AD_Domains.py', wdir='/Users/bawer/Documents/Automation Projects/Test')
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
>     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/Users/bawer/Documents/Automation Projects/Test/Bonsai_AD_Domains.py", line 87, in <module>
>     res = loop.run_until_complete(get_members(group_name))
>   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
>     return future.result()
>   File "/Users/bawer/Documents/Automation Projects/Test/Bonsai_AD_Domains.py", line 70, in get_members
>     attrlist=['employeeID', 'sAMAccountName','objectClass','DistinguishedName'],timeout=10,attrsonly=True,page_size=1000)
>   File "/usr/local/lib/python3.7/site-packages/bonsai-1.2.0-py3.7-macosx-10.14-x86_64.egg/bonsai/asyncio/aioconnection.py", line 64, in _poll
[debug.txt](https://github.com/noirello/bonsai/files/3640251/debug.txt)

>     raise exc
>   File "/usr/local/lib/python3.7/site-packages/bonsai-1.2.0-py3.7-macosx-10.14-x86_64.egg/bonsai/asyncio/aioconnection.py", line 59, in _poll
>     return await asyncio.wait_for(fut, timeout)
>   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.7/site-packages/bonsai-1.2.0-py3.7-macosx-10.14-x86_64.egg/bonsai/asyncio/aioconnection.py", line 45, in _ready
>     res = super().get_result(msg_id)
> bonsai.errors.LDAPError: Operations error. (0x0001 [1])

The query seems to work with JXplorer. It seems the connection might be timing out.

Debug logs attached 

With `is_async=False` I get the following error -

>   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
>     return future.result()
>   File "/Users/bawer/Documents/Automation Projects/Test/Bonsai_AD_Domains.py", line 23, in find_dn
>     async with client.connect(is_async=False) as conn:
> AttributeError: __aexit__

**Comment by noirello** [comment]
Hi, did you try the same search with synchronous connection? Did it produce the same result?

**Comment by reach4bawer** [comment]
> Hi, did you try the same search with synchronous connection? Did it produce the same result?

Update the question with `is_async=False` error as well.

**Comment by noirello** [comment]
> 
> 
> > Hi, did you try the same search with synchronous connection? Did it produce the same result?
> 
> Update the question with `is_async=False` error as well.

You also need to remove await and async keywords to be completely synchronous.

**Comment by noirello** [comment]
> **python: move to OpenSSL 1.1**
That could be the culprit for the crash, but it's just a guess.

**Comment by reach4bawer** [comment]
> > **python: move to OpenSSL 1.1**
> 
> That could be the culprit for the crash, but it's just a guess.

That indeed was the culprit. Had to move to a previous version of python and reinstall OpenSSL.
