### ISSUE TITLE
Add binary for python 3.9

### ISSUE THREAD

**Issue by mchugh19** [noirello/bonsai#44]
When installing with python 3.6, everything went fine. But when we upgraded to python 3.9, installing bonsai resulted in the message 
> error: microsoft visual c++ 14.0 or greater is required

Installing this on my workstation allowed the needed parts to get compiled and bonsai installed successfully. But our company does not allow installing development tools on production servers, so we will need a binary to deploy to our server environment. 

Can you add the required wheel binaries to the pip package for python 3.9?

**Comment by noirello** [comment]
Until a new release, I attach the 3.9 wheels of 1.2.0 for Windows 32bit/64bit [here](https://github.com/noirello/bonsai/files/5684905/bonsai-1.2.0-cp39-win.zip).

**Comment by noirello** [comment]
1.2.1 has been released with 3.9 wheels on PyPI.
