### ISSUE TITLE
Getting ACL for servers

### ISSUE THREAD

**Issue by reach4bawer** [noirello/bonsai#49]
Is there a way to find ACL for AD servers to see what type of access do users have on the active directory server. So something equivalent to Get-ACL Powershell command. An example of details that are returned by this command screenshot -

![image](https://user-images.githubusercontent.com/52763317/116462972-1cd09a00-a838-11eb-99a6-6ee02f496791.png)

Is there a way to pull this information using Bonsai?

**Comment by noirello** [comment]
I'm not familiar with AD enough. If these attributes are part of an LDAP entity, then you should be able to collect them with Bonsai.
This problem seems like more as a how to map AD specific objects to standard LDAP expressions, and not strongly connected to the module.

**Comment by reach4bawer** [comment]
Yea you can see the same attributes in the UI as well.
![image](https://user-images.githubusercontent.com/52763317/117524586-0dfe8b80-af8c-11eb-8384-de56d00c1656.png)

These access control entries are can be seen with the UI without any special permissions. So I am assuming that this might available via cli/programmatically as well.

**Comment by reach4bawer** [comment]
I found this [link](https://stackoverflow.com/a/67414739/9900944) so some of these details are stored.

**Comment by noirello** [comment]
Just released 1.3.0 that has some helper classes for Active Directory. See some details in the [docs](https://bonsai.readthedocs.io/en/latest/advanced.html#utilities-for-active-directory).
