### ISSUE TITLE
GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (Message stream modified)

### ISSUE THREAD

**Issue by kingluo** [noirello/bonsai#78]
I'm setting up a windows AD domain service, and I need to access it via LDAP/GSSAPI/Kerberos.

But I encounter this issue:
ldap_sasl_interactive_bind_s: Local error (-2)
additional info: SASL(-1): generic failure: GSSAPI Error:
Unspecified GSS failure. Minor code may provide more information
(Message stream modified)

I could get the service ticket from Kerberos, but the ldap bind failed.

But I tried Linux kdc/openldap and that's ok.

Does it seem that there is somehow DNS issue? I don't know how to set
up a correct AD domain service. I just need to verify the simplest
ldap bind via Kerberos.

Do you have any idea where I am wrong?

Thank you very much!

**Comment by noirello** [comment]
Sorry, but it looks like some very specific AD-related problem to your environment. I'm not an AD expert. Unfortunately, I can't even point you to a direction, where you can get some answers.

**Comment by kingluo** [comment]
Thanks for your reply! Does bonsai ci test AD with kerberos? I check the .appveyor/ dir, which is AD env setup? Or, could you share some info how to setup an AD with kerberos?  Thank you.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 03/07/2023 02:44 |
| To | ***@***.***> |
| Cc | jinhua ***@***.***>***@***.***> |
| Subject | Re: [noirello/bonsai] GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (Message stream modified) (Issue #78) |

Sorry, but it looks like some very specific AD-related problem to your environment. I'm not an AD expert. Unfortunately, I can't even point you to a direction, where you can get some answers.

**Comment by noirello** [comment]
Yes, it does. You can check the [InstallAD](https://github.com/noirello/bonsai/blob/master/.appveyor/InstallAD.ps1) PowerShell script. It installs and configures a DNS server and a single node Active Directory server.

**Comment by kingluo** [comment]
@noirello No luck too. The setting seems not to do something specific to Kerberos. But then again, have you tried to test bonsai so that it does a successful GSSAPI bind to AD/Kerberos? If so, does it need some configuration or not, e.g. reverse DNS on AD? Or, does bonsai only test with MIT/heimdal Kerberos + openldap?

**Comment by kingluo** [comment]
@noirello If I do not add SPN on AD, then I get "server not found in Kerberos database" error from KDC.

![1678208946907](https://user-images.githubusercontent.com/4401042/223497171-eb16b1e9-cc94-471e-a683-604e40f26657.png)

![1678208966660](https://user-images.githubusercontent.com/4401042/223497201-7f6b51f4-2804-4ed9-8fd7-6b0a2cc0732f.png)


If I set SPN `ldap/bonsai.test` on AD, then I get "message stream modified" from the first bind response from AD.

**Comment by noirello** [comment]
The GSSAPI binding mechanism is tested on Windows with AD. It was quite a while ago, when I configured the appveyor test environment. The only thing that was unexpected a bit, that I had to use the FQDN (`appveyor-vm.bonsai.test`) instead of simply using `bonsai.test`.

**Comment by kingluo** [comment]
> The GSSAPI binding mechanism is tested on Windows with AD. It was quite a while ago, when I configured the appveyor test environment. The only thing that was unexpected a bit, that I had to use the FQDN (`appveyor-vm.bonsai.test`) instead of simply using `bonsai.test`.

@noirello Do you test it manually or via CI? On Windows, GSSAPI uses SSPI automatically, right?

https://github.com/noirello/bonsai/blob/dbbac8d3c4de59002ad562950c7642f148c2f83f/tests/test_ldapconnection.py#L342

**Comment by kingluo** [comment]
@noirello I could use bonsai to access AD over Kerberos now, maybe it's really an FQDN issue, I still need to investigate. Thanks for your hints.
