### ISSUE TITLE
native memleak in `ldap-xplat.c` (`create_krb5_cred`)

### ISSUE THREAD

**Issue by dafanasiev** [noirello/bonsai#84]
You allocate `creds` in [ldap-xplat.c#L213](https://github.com/noirello/bonsai/blob/74ce8f8548a04ab763a21ffaf4bef3ef529ced18/src/_bonsai/ldap-xplat.c#L213) and [ldap-xplat.c#L230](https://github.com/noirello/bonsai/blob/74ce8f8548a04ab763a21ffaf4bef3ef529ced18/src/_bonsai/ldap-xplat.c#L230) but newer free it (need call `krb5_free_cred_contents` if memory is allocated successfully).

**Comment by noirello** [comment]
Thank you, I guess that function call should be added to the end part of the `create_krb5_cred` function.

Could you open a PR with the fix?

**Comment by noirello** [comment]
The PR has been merged to the dev branch.
